
import ThemeProvider from "@/providers/styles-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/theme.css";
import "@/styles/globals.css";
import '@/styles/animations.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}


